# Generated by Django 3.2.5 on 2021-07-04 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('fill_type', models.CharField(max_length=20)),
                ('color1', models.CharField(max_length=20)),
                ('color2', models.CharField(max_length=20)),
                ('angle', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lon', models.IntegerField()),
                ('lat', models.IntegerField()),
                ('areas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.areas')),
            ],
        ),
    ]
