# Generated by Django 3.2.5 on 2021-07-04 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='areas',
        ),
        migrations.AddField(
            model_name='areas',
            name='points',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.point'),
        ),
    ]
